<%@ page contentType="text/html; charset=UTF-8" language="java" %>
<%-- 
  File: country.jsp
  Author: Crystal Long
  Course: CSD-430 • Module 2
  Purpose: Dynamic HTML using JSP Scriptlets. All HTML tags are outside scriptlet blocks.
  Notes: Country = Japan. ≥5 records × 3 fields. Grouped by Region. External CSS.
--%>

<%
  // ===== Runtime Java (no classes/methods/declarations) =====
  final String countryName = "Japan";

  // records: { place, region, highlight }
  java.util.List<String[]> records = new java.util.ArrayList<String[]>();
  records.add(new String[] { "Mt. Fuji",         "Chūbu", "Iconic volcano; views from Lake Kawaguchiko and local flavored ice creams" });
  records.add(new String[] { "Tokyo",            "Kantō", "Skytree, Akihabara, and DisneySea" });
  records.add(new String[] { "Kawagoe",          "Kantō", "“Little Edo” warehouses, first time trying curry, and sweet treats" });
  records.add(new String[] { "Harajuku",         "Kantō", "Meiji Shrine nearby; lolita style fashion hub" });
  records.add(new String[] { "Takeshita Street", "Kantō", "Trendy boutiques and varities of crepes (Harajuku)" });

  // Group by region (preserve encounter order)
  java.util.Map<String, java.util.List<String[]>> byRegion = new java.util.LinkedHashMap<String, java.util.List<String[]>>();
  for (String[] r : records) {
    String region = r[1];
    if (!byRegion.containsKey(region)) {
      byRegion.put(region, new java.util.ArrayList<String[]>());
    }
    byRegion.get(region).add(r);
  }

  // Pre-render table rows as a single String (keeps ALL HTML tags below)
  StringBuilder sb = new StringBuilder();
  for (java.util.Map.Entry<String, java.util.List<String[]>> e : byRegion.entrySet()) {
    String region = e.getKey();
    sb.append("<tr class=\"group-row\"><td colspan=\"3\">Region: ").append(region).append("</td></tr>");
    for (String[] r : e.getValue()) {
      String place = r[0];
      String hl    = r[2];
      sb.append("<tr>")
        .append("<td>").append(place).append("</td>")
        .append("<td><span class=\"chip\">").append(region).append("</span></td>")
        .append("<td>").append(hl).append("</td>")
        .append("</tr>");
    }
  }
  String rowsHtml = sb.toString();
  int recordCount = records.size();
  int fieldCount  = 3;
%>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title><%= countryName %> — Places I Enjoyed Visiting</title>
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>
  <header>
    <h1>Places I Enjoyed Visiting in <%= countryName %></h1>
    <div class="subtitle">Dynamic HTML via JSP scriptlets (all HTML tags are outside scriptlet blocks)</div>
    <div class="meta">
      Records: <strong><%= recordCount %></strong> •
      Fields per record: <strong><%= fieldCount %></strong> •
      Grouped by: <strong>Region</strong>
    </div>
  </header>

  <section class="description">
    <h2>Overall Data Description</h2>
    <p>This table lists memorable places in <strong><%= countryName %></strong>. Each record includes the
      <em>Place</em>, its <em>Region</em>, and a short <em>Highlight</em>. Rows are grouped by <em>Region</em>.</p>

    <h3>Field &amp; Record Descriptions</h3>
    <div class="fields">
      <div class="key">Place</div>   <div>City, district, landmark, or street within the country.</div>
      <div class="key">Region</div>  <div>Geographical area used for grouping (e.g., Kantō, Chūbu).</div>
      <div class="key">Highlight</div><div>What made this place memorable (landmarks, activities, vibes).</div>
    </div>
  </section>

  <section class="table-wrap">
    <table aria-describedby="table-desc">
      <caption id="table-desc" class="sr-only">Memorable places in Japan grouped by region with highlights.</caption>
      <thead>
        <tr><th>Place</th><th>Region</th><th>Highlight</th></tr>
      </thead>
      <tbody><%= rowsHtml %></tbody>
    </table>
  </section>

  <footer class="footer-note">
    Generated by JSP on <%= new java.util.Date() %>.
  </footer>
</body>
</html>
